version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./api
    ports:
      - "8801:8800"
    environment:
      - HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - PASSWORD=${MYSQL_PASSWORD}
      - DATABASE=${MYSQL_DATABASE}
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  mysql_data: 